version: '3.8'
services:

  consumer:
    image: luizmiguelvb/olatcg-backend-blastn
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u main.py'
    env_file:
      - ./env/app.env
      - ./env/db.env
    volumes:
      - ./app:/app
      - ./blast:/blast
      - blastn_storage:/mnt/data/blastn_storage
    networks:
      - olatcg-bridge

volumes:
  blastn_storage:
    name: olatcg-backend_blastn_storage
    external: true

networks:
  olatcg-bridge:
    name: olatcg-bridge
    driver: bridge
    external: true
